language: cpp
env:
  global:
  - DEBSIGN_KEYID=5AE5CD75
  - secure: "DIabgVLlboievYmjdU0IB7jRK9GzxU5ntV2Oxt88hUrT8LmjOEK+rOZ4gShgnc3iQV4s3z5/Mz4iwf7YRvmrWlbnrIiWXzL7i2QH+EJbkctYVFes7265bNd87kvamzNrpM0E9OTwH9baontLA542uGqWMvuB3Tuos4sDUV5xlIA="
  - secure: "b146P9weYgCHaNhPgUO3Dlp5QOnQM+KNml2IWEdJV1YQZbA7V0Pyr/gdD8rnctuHEpApSeQN4/C/SIUr+Lg/+IKVWngvPwkoB3SvvW3/LgWd70TSoDrgvMoMVeMc9zSxps8GHEtwRyGY17YoYU+QD5BnsJ1HSBdk1yr51KfBalA="
  - APT_DEPENDENCIES="doxygen libboost-dev libboost-test-dev libboost-filesystem-dev libboost-system-dev libboost-thread-dev libboost-program-options-dev liblapack-dev gfortran"
  - GIT_DEPENDENCIES=""
  - PPA_URI="stack-of-tasks/snapshot"
  matrix:
  - DIST=unstable
  - DIST=saucy
  - DIST=raring
  - DIST=quantal
  - DIST=precise
notifications:
  hipchat:
    rooms:
      - secure: "jjFl4A7JgT0NwJqfvbNTnGXIHAHC6dYK2BvVSg6gg1ATQwV2DcbY5oVaD++sNQecg0bFKtVtlsOG5yNXSzCVDBYtJUv0JG9jDZAZGjQmDDxLliaiSBbdW10wqPwaF9Bdn5qoE2Ie5zN8Yei9fPGM2nz0EDWHdBGmSOSY6codIjc="
  email:
  - hpp-source@laas.fr
branches:
  only:
  - master
  - debian
script: ./.travis/build
after_success: ./.travis/after_success
compiler: gcc
after_failure: ./.travis/after_failure
before_install: ./.travis/before_install
